FROM node:18.20-alpine AS build-stage

RUN npm config set registry https://registry.npmmirror.com

# 设置工作目录
WORKDIR /app

# 复制package.json和package-lock.json 到容器中
COPY package*.json ./

RUN yarn install

RUN ls -l /app

COPY . .

# 构建项目
RUN npm run build

FROM nginx


# 拷贝构建结果到 Nginx 容器
COPY --from=build-stage /app/dist /usr/share/nginx/html




COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/private/default.conf /etc/nginx/conf.d/default.conf


# 暴露容器的端口
EXPOSE 80

# 启动 Nginx
CMD ["nginx", "-g", "daemon off;"]




